// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuSHdpuUAPO_JT4SPXEa2d2_UckiC4PDA',
    appId: '1:749615488069:web:f41568dffe3ad45720d72c',
    messagingSenderId: '749615488069',
    projectId: 'appdapfirebase',
    authDomain: 'appdapfirebase.firebaseapp.com',
    storageBucket: 'appdapfirebase.firebasestorage.app',
    measurementId: 'G-TR6WHY1EK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNRT9_7qPdENey8wlp9aNReC9wubNhIv4',
    appId: '1:749615488069:android:edfd2b53e68e9dfc20d72c',
    messagingSenderId: '749615488069',
    projectId: 'appdapfirebase',
    storageBucket: 'appdapfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrnCgMwEY_blZa7Hxd2BAyQ6l7uEhFRJc',
    appId: '1:749615488069:ios:0ba64b304b7caaeb20d72c',
    messagingSenderId: '749615488069',
    projectId: 'appdapfirebase',
    storageBucket: 'appdapfirebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrnCgMwEY_blZa7Hxd2BAyQ6l7uEhFRJc',
    appId: '1:749615488069:ios:0ba64b304b7caaeb20d72c',
    messagingSenderId: '749615488069',
    projectId: 'appdapfirebase',
    storageBucket: 'appdapfirebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuSHdpuUAPO_JT4SPXEa2d2_UckiC4PDA',
    appId: '1:749615488069:web:6fe8adc54161b9c920d72c',
    messagingSenderId: '749615488069',
    projectId: 'appdapfirebase',
    authDomain: 'appdapfirebase.firebaseapp.com',
    storageBucket: 'appdapfirebase.firebasestorage.app',
    measurementId: 'G-KQNNMB09DF',
  );
}
